GET http://localhost:8080/api/users

###

GET http://localhost:8080/api/users/2

###
DELETE http://localhost:8080/api/users/3

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "id": 99,
    "login": "Pavani99",
    "password": "#Pavani",
    "age": 23,
    "isDeleted": true
}

###
PUT http://localhost:8080/api/users/3
Content-Type: application/json

{
    "login": "Kunduru",
    "password": "#Kunduru",
    "age": 20,
    "isDeleted": false
}
